---
title: "Step_04_Specific_mdr12_dhps2_Cleaning"
format: html
---

Re-formatting mdr1-2 and dhps-2 based on controls.

```{r}
library(tidyverse)
library(janitor)
```

# Load Data

```{r}
######## dhps-2 ######### 
dhps2_isolates_Haps_final   <- read.csv("05_All_DrugR_Haplotypes/Isolates/Surveys_dhps2_Isolates_Final_Haps.csv")
dhps2_isolates_seq_AA_final <- read.csv("05_All_DrugR_AA_Sequences/Isolates/Surveys_dhps2_final_AA_Aligned_Isolates_Final_Haps.csv", colClasses = "character")
dhps2_isolates_seq_NT_final <- read.csv("05_All_DrugR_NT_Sequences/Isolates/Surveys_dhps2_final_NT_Aligned_Isolates_Final_Haps.csv", colClasses = "character")
######### mdr1-2 ######### 
mdr12_isolates_Haps_final   <- read.csv("05_All_DrugR_Haplotypes/Isolates/Surveys_mdr12_Isolates_Final_Haps.csv")
mdr12_isolates_seq_AA_final <- read.csv("05_All_DrugR_AA_Sequences/Isolates/Surveys_mdr12_final_AA_Aligned_Isolates_Final_Haps.csv", colClasses = "character")
mdr12_isolates_seq_NT_final <- read.csv("05_All_DrugR_NT_Sequences/Isolates/Surveys_mdr12_final_NT_Aligned_Isolates_Final_Haps.csv", colClasses = "character")
```

# dhps-2: Codons 520 and 520.1

```{r}
new_freqs_seq_NT <- dhps2_isolates_seq_NT_final %>% 
  select(-c(X3D7_520, X3D7_520.1)) %>% 
  mutate(Frequency = as.numeric(Frequency), c_ReadCnt = as.numeric(c_ReadCnt)) %>%
  unite("Sequence", X3D7_501:X3D7_654, sep = "") %>% 
  group_by(StudyID, Survey, Marker, Sequence) %>% 
  summarise(Freq_new = sum(Frequency), ReadCnt_new = sum(c_ReadCnt)) %>%
  mutate(Freq_new = ifelse(Freq_new==0.9999997, 1, Freq_new))

dhps2_isolates_seq_NT_CLEANED <- dhps2_isolates_seq_NT_final %>% 
  select(-c(X3D7_520, X3D7_520.1)) %>% 
  mutate(Frequency = as.numeric(Frequency), c_ReadCnt = as.numeric(c_ReadCnt)) %>%
  unite("Sequence", X3D7_501:X3D7_654, sep = "") %>% 
  distinct(StudyID, Sequence, .keep_all = T) %>% select(-c(Frequency, c_ReadCnt)) %>%
  left_join(new_freqs_seq_NT, by = c("StudyID", "Survey", "Marker", "Sequence")) %>% 
  left_join(dhps2_isolates_seq_NT_final, by = c("SeqID", "StudyID", "Haplotype","Survey", "Marker", "Reference", "Haps_NT")) %>% 
  select(-c(Sequence, Frequency, c_ReadCnt, X3D7_520.1)) %>% 
  rename(Frequency = Freq_new, c_ReadCnt = ReadCnt_new) %>%
  select(SeqID, StudyID, Haplotype, Frequency, c_ReadCnt, everything()) 

dhps2_isolates_CLEANED_data <- dhps2_isolates_seq_NT_CLEANED %>% select(-c(X3D7_501:X3D7_654, Haps_NT))

dhps2_isolates_seq_AA_CLEANED <- dhps2_isolates_seq_AA_final %>% 
  select(-c(Frequency, c_ReadCnt)) %>%
  right_join(dhps2_isolates_CLEANED_data, by = c("SeqID", "StudyID", "Haplotype", "Survey", "Marker", "Reference")) %>%
  select(SeqID, StudyID, Haplotype, Frequency, c_ReadCnt, everything()) 
    
dhps2_isolates_Haps_final_CLEANED <- dhps2_isolates_Haps_final %>% 
  select(-c(Frequency, c_ReadCnt, Haplotype)) %>%
  right_join(dhps2_isolates_CLEANED_data, by = c("SeqID", "StudyID", "Survey", "Marker", "Reference")) %>%
  select(SeqID, StudyID, Haplotype, Frequency, c_ReadCnt, everything())
```

# mdr1-2: Remove X3D7_1077, X3D7_1078, X3D7_1079

```{r}
mdr12_new_freqs_seq_NT <- mdr12_isolates_seq_NT_final %>% 
  mutate(Frequency = as.numeric(Frequency), c_ReadCnt = as.numeric(c_ReadCnt)) %>%
  unite("Sequence", X3D7_939:X3D7_1076, sep = "") %>% 
  group_by(StudyID, Survey, Marker, Sequence) %>% 
  summarise(Freq_new = sum(Frequency), ReadCnt_new = sum(c_ReadCnt)) %>%
  mutate(Freq_new = ifelse(Freq_new>0.99999, 1, Freq_new))

mdr12_isolates_seq_NT_CLEANED <- mdr12_isolates_seq_NT_final %>% 
  mutate(Frequency = as.numeric(Frequency), c_ReadCnt = as.numeric(c_ReadCnt)) %>%
  unite("Sequence", X3D7_939:X3D7_1076, sep = "") %>% 
  distinct(StudyID, Sequence, .keep_all = T) %>% select(-c(Frequency, c_ReadCnt)) %>%
  left_join(mdr12_new_freqs_seq_NT, by = c("StudyID", "Survey", "Marker", "Sequence")) %>% 
  left_join(mdr12_isolates_seq_NT_final, by = c("SeqID", "StudyID", "Haplotype","Survey", "Marker", "Reference", "Haps_NT")) %>% 
  select(-c(Sequence, Frequency, c_ReadCnt)) %>% 
  rename(Frequency = Freq_new, c_ReadCnt = ReadCnt_new) %>%
  select(SeqID, StudyID, Haplotype, Frequency, c_ReadCnt, everything()) 

mdr12_isolates_CLEANED_data <- mdr12_isolates_seq_NT_CLEANED %>% select(-c(X3D7_939:X3D7_1076, Haps_NT))

mdr12_isolates_seq_AA_CLEANED <- mdr12_isolates_seq_AA_final %>% 
  select(-c(Frequency, c_ReadCnt)) %>%
  right_join(mdr12_isolates_CLEANED_data, by = c("SeqID", "StudyID", "Haplotype", "Survey", "Marker", "Reference")) %>%
  select(SeqID, StudyID, Haplotype, Frequency, c_ReadCnt, everything()) 
    
mdr12_isolates_Haps_final_CLEANED <- mdr12_isolates_Haps_final %>% 
  select(-c(Frequency, c_ReadCnt, Haplotype)) %>%
  right_join(mdr12_isolates_CLEANED_data, by = c("SeqID", "StudyID", "Survey", "Marker", "Reference")) %>%
  select(SeqID, StudyID, Haplotype, Frequency, c_ReadCnt, everything())
```

# Write new files

```{r}
write.csv(dhps2_isolates_seq_NT_CLEANED, "05_All_DrugR_NT_Sequences/Isolates/Surveys_dhps2_final_NT_Aligned_Isolates_Final_Adjusted_Haps.csv", row.names = F)
write.csv(dhps2_isolates_seq_AA_CLEANED, "05_All_DrugR_AA_Sequences/Isolates/Surveys_dhps2_final_AA_Aligned_Isolates_Final_Adjusted_Haps.csv", row.names = F)
write.csv(dhps2_isolates_Haps_final_CLEANED, "05_All_DrugR_Haplotypes/Isolates/Surveys_dhps2_Isolates_Final_Adjusted_Haps.csv", row.names = F)

write.csv(dhps2_repeats_seq_NT_CLEANED, "05_All_DrugR_NT_Sequences/Repeats/Surveys_dhps2_final_NT_Aligned_Repeats_Final_Adjusted_Haps.csv", row.names = F)
write.csv(dhps2_repeats_seq_AA_CLEANED, "05_All_DrugR_AA_Sequences/Repeats/Surveys_dhps2_final_AA_Aligned_Repeats_Final_Adjusted_Haps.csv", row.names = F)
write.csv(dhps2_repeats_Haps_final_CLEANED, "05_All_DrugR_Haplotypes/Repeats/Surveys_dhps2_Repeats_Final_Adjusted_Haps.csv", row.names = F)
```
